name: My caller workflow

on:
  workflow_dispatch: {}

jobs:
  my_job:
    uses: ./.github/workflows/reusable-workflow.yml
  the_user:
    runs-on: ubuntu-latest
    needs: my_job
    steps:
      - run: echo "results=${{ toJSON(needs.my_job.outputs) }}"
