name: failing behaviour

on:
  workflow_dispatch: {}

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  second:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
  dependent:
    needs: [first, second]
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - run: |
          echo "first: result=${{ needs.first.result }}"
          echo "second: result=${{ needs.second.result }}"

