name: Matrix

on:
  workflow_dispatch: {}

jobs:
  my_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pet: [cat, dog]
        color: [blue, green]
        include:
          - pet: cat
            addition: hello
    steps:
      - run: echo "${{ toJSON(matrix) }}"
