name: Matrix

on:
  workflow_dispatch: {}

jobs:
  my_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pet: [cat, dog]
        color: [pink, blue]
        include:
          - color: green
          - color: pink
            pet: bird
          - color: yellow
            pet: rabbit
          - color: green
            pet: horse
    steps:
      - run: echo ${{ toJSON(matrix) }}
