name: Matrix

on:
  workflow_dispatch: {}

jobs:
  my_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pet: [dog, cat]
        color: [blue, pink]
        include:
          - color: green
          - color: blue
            addition: hello
    steps:
      - run: echo "${{ toJSON(matrix) }}"
