name: I will delete myself

on:
  workflow_dispatch: {}

jobs:
  my_job:
    runs-on: ubuntu-latest
    env:
        BOT_MAIL: "action@noreply"
        BOT_USER: "[github action]"
    steps:
        - uses: actions/checkout@v3
        - run: |
            rm .github/workflows/self-deleting.yml
            git add .github/workflows/self-deleting.yml
            git commit -m 'delete workflow'
        - run: |
            git config --global user.name "${BOT_USER}"
            git config --global user.email "${BOT_MAIL}"
            git push
