name: Status check functions and steps context

on:
  workflow_dispatch: {}

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: will fail
        id: failing_step
        continue-on-error: true
        run: exit 1
      - name: after failed step
        if: ${{ always() }}
        run: |
          echo "conclusion: ${{ steps.failing_step.conclusion }}"
          echo "outcome: ${{ steps.failing_step.outcome }}"
      - name: will also fail (no continue_on_error)
        id: next_failing
        run: exit 1
      - name: after failed step without continue
        if: ${{ failure() }}
        run: |
          echo "I ran"
